baseURL = "http://example.org/"
languageCode = "en-gb"
title = "TotallyMoney"
theme = "ga-hugo-theme"
paginate = 3
paginatePath = "guides"

[ taxonomies ]
  tag = "tags"
  category = "categories"

[ menu ]
  [[ menu.main ]]
    name = "Guides Home"
    weight = 1
    identifier = "home"
    url = "/"

  [[ menu.main ]]
    name = "Credit Report"
    weight = 2
    identifier = "free-credit-report"
    url = "/free-credit-report/"

  [[ menu.main ]]
    name = "Credit Cards"
    weight = 3
    identifier = "credit-cards"
    url = "/credit-cards/"

  [[ menu.main ]]
    name = "Loans"
    weight = 4
    identifier = "loans"
    url = "/loans/"

  [[ menu.main ]]
    name = "Mortgages"
    weight = 5
    identifier = "mortgages"
    url = "/mortgages/"

[ params ]
  description = "Take control with access to your full credit report. No credit card needed. See the best credit offers you could get on credit cards, loans &amp; mortgages."
