---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: https://webhook.site/d1a75e08-3d77-4005-a652-ac86c82df6ab
sections:
- type: document
  path: content/index.html
  label: Home
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
- type: heading
  label: Guides
- type: directory
  path: content/free-credit-report
  label: Free Credit Report
  create: all
  match: "**/*"
  templates:
  - credit-report-guide
- type: directory
  path: content/mortgages
  label: Mortgages
  create: all
  match: "**/*"
  templates:
  - mortgages-guide
- type: directory
  path: content/credit-cards
  label: Credit Cards
  create: all
  match: "**/*"
  templates:
  - credit-cards-guide
- type: directory
  path: content/loans
  label: Loans
  create: all
  match: "**/*"
  templates:
  - loans-guide
- type: heading
  label: Blog
- type: heading
  label: Press Centre
- type: heading
  label: Legal
upload_dir: static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
  publish_command: hugo -d public
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.51
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.51
  preview_output_directory: public
  output_directory: public
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: '0.51'
